<a href="https://colab.research.google.com/github/Simonpnce57/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [15]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [16]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [17]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [18]:
# Create a list of at least 10 column names to use as X data

selected_columns = ['Age', 'DistanceFromHome', 'HourlyRate', 'JobRole','JobLevel', 'NumCompaniesWorked', 'PercentSalaryHike', 'TotalWorkingYears', 'YearsAtCompany', 'YearsSinceLastPromotion']



# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes

Age                         int64
DistanceFromHome            int64
HourlyRate                  int64
JobRole                    object
JobLevel                    int64
NumCompaniesWorked          int64
PercentSalaryHike           int64
TotalWorkingYears           int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
dtype: object

In [19]:
#chnage the data type of the JobRole column to int64
X_df['JobRole'] = X_df['JobRole'].astype('category').cat.codes

<ipython-input-19-3b3d9478d8bd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['JobRole'] = X_df['JobRole'].astype('category').cat.codes

In [21]:
# Split the data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [22]:
# Convert your X data to numeric data types however you see fit Add new code cells as necessary

X_df = X_df.astype('float64')
X_df.dtypes

Age                        float64
DistanceFromHome           float64
HourlyRate                 float64
JobRole                    float64
JobLevel                   float64
NumCompaniesWorked         float64
PercentSalaryHike          float64
TotalWorkingYears          float64
YearsAtCompany             float64
YearsSinceLastPromotion    float64
dtype: object

In [24]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)

department = attrition_df[['Department']]
department_encoded = encoder.fit_transform(department)

encoder = OneHotEncoder(sparse=False)
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)


# Fit the encoder to the training data
enc = OneHotEncoder(sparse=False)

# Create two new variables by applying the encoder to the training and testing data

enc.fit(y_df)
y_train = enc.transform(y_df)
y_test = enc.transform(y_df)

y_train_encoded[:5]
y_test_encoded[:5]

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.]])

In [27]:
# Create a OneHotEncoder for the Attrition column
from sklearn.preprocessing import OneHotEncoder

attrition = attrition_df[['Attrition']]
attrition_encoded = encoder.fit_transform(attrition)

encoder = OneHotEncoder(sparse=False)
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)


# Fit the encoder to the training data
enc = OneHotEncoder(sparse=False)


# Create two new variables by applying the encoder
# to the training and testing data

enc.fit(y_df)
y_train = enc.transform(y_df)
y_test = enc.transform(y_df)

y_train_encoded[:5]
y_test_encoded[:5]

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., 1., 1., 0., 1., 0., 0., 1.],
       [0., 1., 1., 0., 1., 0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 1., 1., 0.]])

## Create, Compile, and Train the Model

In [28]:
# Find the number of columns in the X training data
number_input_features = len(X_train.columns)
number_input_features


# Create the input layer
input = layers.Input(shape=(number_input_features,))



# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(input)
shared_layer2 = layers.Dense(units=32, activation='relu')(shared_layer1)

In [29]:
# Create a branch for Department with a hidden layer and an output layer
department_input = layers.Input(shape=(number_input_features,))
department_hidden = layers.Dense(units=64, activation='tanh')(department_input)
department_output = layers.Dense(units=2, activation='relu')(department_hidden)
department_model = Model(inputs=department_input, outputs=department_output)

# Create the hidden layer
hidden_layer = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=2, activation='sigmoid')(hidden_layer)

In [30]:
# Create a branch for Attrition with a hidden layer and an output layer
attrition_input = layers.Input(shape=(number_input_features,))
attrition_hidden = layers.Dense(units=64, activation='tanh')(attrition_input)
attrition_output = layers.Dense(units=2, activation='relu')(attrition_hidden)
attrition_model = Model(inputs=attrition_input, outputs=attrition_output)

# Create the hidden layer
hidden_layer = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=2, activation='sigmoid')(hidden_layer)

In [31]:
print(X_train_scaled.shape)
print(y_train_encoded.shape)

(1176, 10)
(1470, 10)

In [32]:
# Define input layers
department_input = layers.Input(shape=(number_input_features,))
attrition_input = layers.Input(shape=(number_input_features,))

# Shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(department_input)  # Connect to department_input
shared_layer2 = layers.Dense(units=32, activation='relu')(shared_layer1)

# Department branch
department_hidden = layers.Dense(units=64, activation='relu')(shared_layer2)  # Connect to shared_layer2
department_output = layers.Dense(units=2, activation='relu')(department_hidden)

# Attrition branch
attrition_hidden = layers.Dense(units=64, activation='relu')(shared_layer2)  # Connect to shared_layer2
attrition_output = layers.Dense(units=2, activation='relu')(attrition_hidden)

# Create the model
model = Model(inputs=[department_input, attrition_input], outputs=[department_output, attrition_output])

In [85]:
# Create the model
model = Model(inputs=[department_input, attrition_input], outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "functional_23"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_22            │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_76 (Dense)          │ (None, 64)             │            704 │ input_layer_22[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_77 (Dense)          │ (None, 32)             │          2,080 │ dense_76[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_78 (Dense)          │ (None, 64)             │          2,112 │ dense_77[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_80 (Dense)          │ (None, 64)             │          2,112 │ dense_77[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_23            │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_79 (Dense)          │ (None, 2)              │            130 │ dense_78[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_81 (Dense)          │ (None, 2)              │            130 │ dense_80[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 7,268 (28.39 KB)

 Trainable params: 7,268 (28.39 KB)

 Non-trainable params: 0 (0.00 B)

In [86]:
# Train the model
model.fit([X_train_scaled, X_train_scaled], [y_train_encoded, y_train_encoded], epochs=10, batch_size=32)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 1176, 1176
'y' sizes: 1470, 1470

In [ ]:
# Evaluate the model with the testing data
model_loss, model_accuracy = model.evaluate([X_test_scaled, X_test_scaled], [y_test_encoded, y_test_encoded])
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 [==============================] - 0s 3ms/step - loss: 4.1624 - department_output_loss: 3.1143 - attrition_output_loss: 1.0481 - department_output_accuracy: 0.5272 - attrition_output_accuracy: 0.8261

[4.162380218505859,
 3.114327907562256,
 1.0480519533157349,
 0.5271739363670349,
 0.8260869383811951]

In [ ]:
# Print the accuracy for both department and attrition

Department predictions accuracy: 0.5271739363670349
Attrition predictions accuracy: 0.8260869383811951

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.